config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :restaurants
  end
  resources :restaurants, only: [ :index, :new, :show, :create ] do
    resources :reviews, only: [ :new, :create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_interger: true }
  validates :rating, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(restaurant_params)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_reviews_path(@review)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_review
    @review = Review.find(review_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <%= f.text_field :name %>
  <%= f.text_field :address %>
  <%= f.text_field :phone_number %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"]%>
  <%= f.submit %>
<% end %>

<%= link_to "<<<Back to restaurants list", restaurants_path %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>My list of restaurants</h1>
  <% @restaurants.each do |restaurant| %>
  <div>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    <p><%= restaurant.address %></p>
    <p><%= restaurant.phone_number %></p>
    <p><%= restaurant.category %></p>
  </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
   <% end %>
  <%= f.text_field :name %>
  <%= f.text_field :address %>
  <%= f.text_field :phone_number %>
  <%= f.text_field :category %>
  <%= f.submit %>

<% end %>


<%= link_to "<<<Back to restaurants list", restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>

<div class="btn btn-primary">
  <%= link_to "See the comments", restaurant_reviews_path(@restaurant) %>
</div>
</div>

<%= link_to "<<<Back to restaurants list", restaurants_path %>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/index.html.erb
<div class="container">
  <h1><%= "My list of #{params[:name]}'s comments" %></h1>
  <% @reviews.each do |review| %>
  <div>
    <h2><%= review.content %></h2>
    <p><%= review.rating %></p>
  </div>
  <% end %>
</div>

<%= link_to "Add a comment to this restaurant", new_restaurant_review_path %>

<%= link_to "<<<Back to #{params[:name]} page", restaurant_path(params[:restaurant_id]) %>

app/views/reviews/new.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
<% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :content %>
  <%= f.input :rating, collection: (0..5)%>
  <%= f.submit %>
<% end %>


<%= link_to "<<<Back to #{params[:name]} page", restaurant_path(params[:restaurant_id]) %>